Repository MIT-Emerging-Talent/ET6-foundations-group-26, pull requests merged in 2024-12, with the labels that each got.

#6 adding_readme
  README.md
  assets/cat.gif
  assets/cat2.gif
  assets/cat3.gif
  assets/cat4.gif
  assets/cat5.gif
  assets/hi.gif
  collaboration/guide/0_repository_setup.md
Labels: documentation

#12 Fizz buzz
  solutions/fizz_buzz.py
  solutions/tests/test_fizz_buzz.py
Labels: bug, documentation

#33 Search Insert Position Problem Solution
  solutions/search_insert_position.py
  solutions/tests/test_search_insert_position.py
Labels: new challenge
