Repository MIT-Emerging-Talent/ET6-foundations-group-26, pull requests merged in 2025-01, with the labels that each got.

#27 count_vowels
  .vscode/settings.json
  solutions/count_vowels.py
  solutions/tests/test_count_vowels.py
Labels: new challenge

#37 Add two sum function
  solutions/tests/test_two_sum.py
  solutions/two_sum.py
Labels: enhancement, new challenge

#29 Caesar encryption
  solutions/caesar_encryption.py
  solutions/tests/test_caesar_encryption.py
Labels: new challenge

#47 Majority element
  solutions/majority_element.py
  solutions/tests/test_majority_element.py
Labels: new challenge

#43 Palindrome checker
  solutions/palindrome_checker.py
  solutions/tests/test_palindrome_checker.py
Labels: new challenge

#45 Add binary code challenge
  solutions/add_binary.py
  solutions/tests/test_add_binary.py
Labels: new challenge

#49 Happy number
  solutions/happy_number.py
  solutions/tests/test_happy_number.py
Labels: new challenge

#42 reverse string
  solutions/reverse_string.py
  solutions/tests/test_reverse_string.py
Labels: new challenge

#53 52 bubble sort
  solutions/bubble_sort.py
  solutions/tests/test_bubble_sort.py
Labels: new challenge

#55 54 insertion sort
  solutions/insertion_sort.py
  solutions/tests/test_insertion_sort.py
Labels: new challenge

#65 5 working on the constraints file
  collaboration/constraints.md
Labels: documentation

#64 Edit retrospective
  collaboration/retrospective.md
Labels: documentation

#68 amro
  solutions/convert_temperature.py
  solutions/steps_to_floor.py
  solutions/tests/test_convert_temperature.py
  solutions/tests/test_steps_to_floor.py
Labels: enhancement

#70 Update count vowels
  solutions/count_vowels.py
  solutions/tests/test_count_vowels.py
Labels: enhancement

#71 add 2 lines infront of my filse
  solutions/fizz_buzz.py
  solutions/reverse_string.py
  solutions/tests/test_fizz_buzz.py
  solutions/tests/test_reverse_string.py
Labels: enhancement

#72 Update majority element
  solutions/majority_element.py
  solutions/tests/test_majority_element.py
Labels: enhancement
